# Generated by Django 3.1 on 2024-10-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20241030_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cetegory_name',
            new_name='category_name',
        ),
    ]
